Vet clinic database: query and update animals table
sajid-munawar/Vet_clinic_database pull request #2
Opened 2022-08-26 13:46 UTC by sajid-munawar

![Screenshot from 2022-08-26 09-54-45](https://user-images.githubusercontent.com/66992901/186917699-761405ad-6887-4c02-8888-ab4422f0b963.png)
![Screenshot from 2022-08-26 09-55-55](https://user-images.githubusercontent.com/66992901/186917724-7da6613e-00f6-4d4d-a65a-fc98a8833bc2.png)
![Screenshot from 2022-08-26 09-56-13](https://user-images.githubusercontent.com/66992901/186917750-c83cfb1b-e2b6-43ac-bf42-f598a37ee450.png)
![Screenshot from 2022-08-26 09-56-31](https://user-images.githubusercontent.com/66992901/186917767-776dbf22-0bf5-40a9-b725-916e3fb5e898.png)
![Screenshot from 2022-08-26 09-56-43](https://user-images.githubusercontent.com/66992901/186917787-43832ea4-b875-4a82-8e9a-9e26e8da43ca.png)
![Screenshot from 2022-08-26 09-56-53](https://user-images.githubusercontent.com/66992901/186917801-6a4b60d0-0c8e-45b7-8791-31aba1661900.png)
![Screenshot from 2022-08-26 09-57-06](https://user-images.githubusercontent.com/66992901/186917815-b21f74a8-4295-40b8-82cc-cee5670b7bed.png)
![Screenshot from 2022-08-26 09-57-17](https://user-images.githubusercontent.com/66992901/186917832-e7e28d6a-3064-4724-9fb0-1ada5d146129.png)

2022-08-26 13:59 UTC, vechicin requested changes
# Hi @sajid-munawar ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good job updating the table and making most of the queries necessary required in this milestone.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 13:59 UTC, vechicin commented on data.sql
> +where not species = 'digimon';
According to the project requirements, this query should be added to the `queries.sql` file. Please fix this.

2022-08-26 13:59 UTC, vechicin commented on queries.sql
>  /*Queries that provide answers to the questions from all projects.*/
According to the project requirements, the following query should be present. Please add it.

<img width="531" alt="Screen Shot 2022-08-26 at 8 52 05" src="https://user-images.githubusercontent.com/82426682/186919093-f2c98b91-31df-42a2-868b-192972b5e771.png">

2022-08-26 13:59 UTC, vechicin commented on queries.sql
According to the project requirements, the following query should be present, please add it.

<img width="343" alt="Screen Shot 2022-08-26 at 8 53 39" src="https://user-images.githubusercontent.com/82426682/186919433-da1ab5d3-d12a-455a-a640-e97901f039a5.png">

2022-08-26 13:59 UTC, vechicin commented on queries.sql
> -
According to the project requirements, the following query should be present, please add it.

<img width="575" alt="Screen Shot 2022-08-26 at 8 55 49" src="https://user-images.githubusercontent.com/82426682/186919908-f7b600d3-2745-472e-9701-adfc0db8d04f.png">

2022-08-27 04:29 UTC, danielufeli approved these changes
Hi @sajid-munawar ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Code ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 06:28 UTC, merged